### ISSUE TITLE
域名更新！！

### ISSUE THREAD

**Issue by cysk003** [x-spiders/aiss-spider#20]
今日更新发现域名更新，重新抓取了下，分享给各位！！

https://com-wuwei-aiss.oss-cn-beijing.aliyuncs.com

在download_pictures.py里修改即可！！

**Comment by cysk003** [comment]
今日域名更新
https://aiss.obs.cn-north-1.myhwclouds.com

**Comment by kingswjw** [comment]
为什么下载下来的图片是loading状态

**Comment by kingswjw** [comment]
域名已经更新，下载后目录都有，只是所有图片都是loading状态；
url = "https://aiss.obs.cn-north-1.myhwclouds.com/picture/%s/%s/%s.jpg" % (catalog, issue, pic_idx)

**Comment by kingswjw** [comment]
问题已经找到，Charles设置错误，大神厉害了~

**Comment by PLQin** [comment]
566666

**Comment by WeiZhiJing** [comment]
坐等更新

**Comment by LuckyTwist** [comment]
兄弟域名又改了吗? 下不了

**Comment by Deepblue1996** [comment]
还没有更新吗

**Comment by cysk003** [comment]
域名同上，没变化！！

**Comment by cysk003** [comment]
今日域名更新
http://aiss.obs.cn-north-1.myhwclouds.com

**Comment by cysk003** [comment]
2019/05/15域名更新
https://aiss.obs.cn-north-1.myhwclouds.com
在download_pictures.py里修改即可！！

**Comment by sunqicn** [comment]
mk

**Comment by LambertW** [comment]
域名好像又更新了？楼主能否抽时间看看 ？
另外，这个APP有没有地方下载。看起来找不到了...

**Comment by rinkengou** [comment]
C:\Users\Abao>python d:\aiss\run.py
Traceback (most recent call last):
  File "d:\aiss\run.py", line 8, in <module>
    download_info()
  File "d:\aiss\download_info.py", line 10, in download_info
    page_json = download_page(page)
  File "d:\aiss\download_info.py", line 25, in download_page
    return rsp.json()
  File "C:\Users\Abao\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Abao\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Abao\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Abao\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


请问大佬，运行出现这个错误怎么办啊 ？？@cysk003。跪求解决办法。谢谢
